x="hello world" #string
x=20 #integer
x=20.5 #float
x=1j #complex
x=["apple", "banana", "cherry"] #list
x=("apple", "banana", "cherry") #tuple
x=range(6) #range
x={"name": "John", "age":36} #dictionary
x={"apple", "banana", "cherry"} #set
x=frozenset({"apple", "banana", "cherry"}) #frozenset
x=True #boolean
x=b"hello" #bytes
x=bytearray(5) #bytearray
x=memoryview(bytes(5)) #memoryview
x=None #nonetype

x = str("Hello World") #string
x = int(20) #int
x = float(20.5)	#float
x = complex(1j)	#complex
x = list(("apple", "banana", "cherry"))	#list
x = tuple(("apple", "banana", "cherry"))	#tuple
x = range(6)	#range	
x = dict(name="John", age=36)	#dict	
x = set(("apple", "banana", "cherry"))	#set	
x = frozenset(("apple", "banana", "cherry"))	#frozenset	
x = bool(5)	#bool	
x = bytes(5)	#bytes	
x = bytearray(5)	#bytearray	
x = memoryview(bytes(5))	#memoryview